const players = [
  // WOMEN
  {
    id: 1,
    gender: "women",
    name: "María López",
    position: "Midfielder",
    age: 18,
    nationality: "Ecuador",
    height: "165 cm",
    weight: "58 kg",
    status: "Available",
    type: "Freshman",
    gpa: "3.8",
    mentions: "Team captain · National finalist · Leadership",
    sprint5: "1.05 s",
    sprint10: "1.85 s",
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: 3,
    gender: "women",
    name: "Sofía Andrade",
    position: "Center Back",
    age: 19,
    nationality: "Ecuador",
    height: "172 cm",
    weight: "64 kg",
    status: "Committed",
    type: "Transfer",
    gpa: "3.6",
    mentions: "Defensive leader · NJCAA experience",
    sprint5: "1.08 s",
    sprint10: "1.90 s",
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: 5,
    gender: "women",
    name: "Valentina Ruiz",
    position: "Forward",
    age: 17,
    nationality: "Colombia",
    height: "163 cm",
    weight: "56 kg",
    status: "Available",
    type: "Freshman",
    gpa: "3.9",
    mentions: "Top scorer · Explosive speed",
    sprint5: "0.98 s",
    sprint10: "1.72 s",
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },

  // MEN
  {
    id: 2,
    gender: "men",
    name: "Lucas Fernández",
    position: "Center Back",
    age: 19,
    nationality: "Argentina",
    height: "182 cm",
    weight: "75 kg",
    status: "Available",
    type: "Freshman",
    gpa: "3.6",
    mentions: "Strong aerial game · Defensive leader",
    sprint5: "1.00 s",
    sprint10: "1.78 s",
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: 4,
    gender: "men",
    name: "Andrés Molina",
    position: "Forward",
    age: 20,
    nationality: "Colombia",
    height: "178 cm",
    weight: "72 kg",
    status: "Committed",
    type: "Transfer",
    gpa: "3.4",
    mentions: "Clinical finisher · College experience",
    sprint5: "0.97 s",
    sprint10: "1.70 s",
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  },
  {
    id: 6,
    gender: "men",
    name: "Diego Ríos",
    position: "Defensive Midfielder",
    age: 21,
    nationality: "Chile",
    height: "180 cm",
    weight: "74 kg",
    status: "Available",
    type: "Transfer",
    gpa: "3.5",
    mentions: "High work rate · Tactical intelligence",
    sprint5: "1.02 s",
    sprint10: "1.82 s",
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ"
  }
];

localStorage.setItem("players", JSON.stringify(players));
